apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  namespace:  "{{ .Values.nodejs.namespace }}"
spec:
  type: "{{ .Values.service.spec.type }}"
  selector:
    app: "{{ .Values.service.name }}"
  ports:
   -  protocol: "{{ .Values.service.spec.ports.protocol }}"
      port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}