apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: nstest
data:
  # Values must be encoded as base64 (for example: echo -n 'wordToEncode' | base64)
  DB-USERNAME: dGhlVXNlcm5hbWU=
  DB-PASSWORD: dGhlUGFzc3dvcmQ=